def throw_error(error_msg):
    raise Exception(error_msg)